version: "3.6"

services:

  cadvisor:
    image: google/cadvisor:latest
    restart: unless-stopped
    volumes:
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run:/var/run:ro
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086

  influx:
    image: influxdb:1.8
    restart: unless-stopped
    environment:
     - INFLUXDB_DB=cadvisor 
    volumes:
     - influxdb-storage:/var/lib/influxdb

  grafana:
    image: grafana/grafana:9.0.4
    restart: unless-stopped
    ports:
      - 3001:3000
    volumes:
     - grafana-storage:/var/lib/grafana

volumes:
  influxdb-storage:
  grafana-storage:
